//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDER()
        {
            this.ORDERS_DETAIL = new HashSet<ORDERS_DETAIL>();
        }
    
        public int Orders_ID { get; set; }
        public Nullable<System.DateTime> Orders_Date { get; set; }
        public Nullable<int> Customers_ID { get; set; }
        public Nullable<byte> Status { get; set; }
        public string Note { get; set; }
        public Nullable<byte> Payment_Method { get; set; }
        public Nullable<byte> Payment_Status { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERS_DETAIL> ORDERS_DETAIL { get; set; }
    }
}
