//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERS_DETAIL
    {
        public int OrdersDetail_ID { get; set; }
        public Nullable<int> Orders_ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public Nullable<int> Product_Num { get; set; }
    
        public virtual ORDER ORDER { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
